language: c

env:
    global:
        - RACKET_DIR=~/racket
    matrix:
        - RACKET_VERSION=6.1.1

before_install:
    - git clone https://github.com/greghendershott/travis-racket.git
    - cat travis-racket/install-racket.sh | bash
    - export PATH="${RACKET_DIR}/bin:${PATH}"
    - rm -rf travis-racket # configlet thinks this is an exercise and complains

install:

before_script:

script:
    - ./bin/check-exercises.sh
    - ./bin/fetch-configlet
    - ./bin/configlet .

after_script:
